var place_data = [
    {
        tag: "taipei_city",
        place: "臺北市",
        low: "暫無資料",
        high: "暫無資料",
        weather: "暫無資料",
        weatherIcon: 0,
        PoP: -1,
        AIQ: -1,
        Status: "暫無資料",
        PM25: -1

    },
    {
        tag: "new_taipei_city",
        place: "新北市",
        low: "暫無資料",
        high: "暫無資料",
        weather: "暫無資料",
        weatherIcon: 0,
        PoP: -1,
        AIQ: -1,
        Status: "暫無資料",
        PM25: -1
    },
    {
        tag: "taichung_city",
        place: "臺中市",
        low: "暫無資料",
        high: "暫無資料",
        weather: "暫無資料",
        weatherIcon: 0,
        PoP: -1,
        AIQ: -1,
        Status: "暫無資料",
        PM25: -1
    },
    {
        tag: "tainan_city",
        place: "臺南市",
        low: "暫無資料",
        high: "暫無資料",
        weather: "暫無資料",
        weatherIcon: 0,
        PoP: -1,
        AIQ: -1,
        Status: "暫無資料",
        PM25: -1
    },
    {
        tag: "kaohsiung_city",
        place: "高雄市",
        low: "暫無資料",
        high: "暫無資料",
        weather: "暫無資料",
        weatherIcon: 0,
        PoP: -1,
        AIQ: -1,
        Status: "暫無資料",
        PM25: -1
    },
    {
        tag: "keelung_city",
        place: "基隆市",
        low: "暫無資料",
        high: "暫無資料",
        weather: "暫無資料",
        weatherIcon: 0,
        PoP: -1,
        AIQ: -1,
        Status: "暫無資料",
        PM25: -1
    },
    {
        tag: "taoyuan_country",
        place: "桃園市",
        low: "暫無資料",
        high: "暫無資料",
        weather: "暫無資料",
        weatherIcon: 0,
        PoP: -1,
        AIQ: -1,
        Status: "暫無資料",
        PM25: -1
    },
    {
        tag: "hsinchu_city",
        place: "新竹市",
        low: "暫無資料",
        high: "暫無資料",
        weather: "暫無資料",
        weatherIcon: 0,
        PoP: -1,
        AIQ: -1,
        Status: "暫無資料",
        PM25: -1
    },
    {
        tag: "hsinchu_country",
        place: "新竹縣",
        low: "暫無資料",
        high: "暫無資料",
        weather: "暫無資料",
        weatherIcon: 0,
        PoP: -1,
        AIQ: -1,
        Status: "暫無資料",
        PM25: -1
    },
    {
        tag: "miaoli_country",
        place: "苗栗縣",
        low: "暫無資料",
        high: "暫無資料",
        weather: "暫無資料",
        weatherIcon: 0,
        PoP: -1,
        AIQ: -1,
        Status: "暫無資料",
        PM25: -1
    },
    {
        tag: "changhua_country",
        place: "彰化縣",
        low: "暫無資料",
        high: "暫無資料",
        weather: "暫無資料",
        weatherIcon: 0,
        PoP: -1,
        AIQ: -1,
        Status: "暫無資料",
        PM25: -1
    },
    {
        tag: "nantou_country",
        place: "南投縣",
        low: "暫無資料",
        high: "暫無資料",
        weather: "暫無資料",
        weatherIcon: 0,
        PoP: -1,
        AIQ: -1,
        Status: "暫無資料",
        PM25: -1
    },
    {
        tag: "yunlin_country",
        place: "雲林縣",
        low: "暫無資料",
        high: "暫無資料",
        weather: "暫無資料",
        weatherIcon: 0,
        PoP: -1,
        AIQ: -1,
        Status: "暫無資料",
        PM25: -1
    },
    {
        tag: "chiayi_city",
        place: "嘉義市",
        low: "暫無資料",
        high: "暫無資料",
        weather: "暫無資料",
        weatherIcon: 0,
        PoP: -1,
        AIQ: -1,
        Status: "暫無資料",
        PM25: -1
    },
    {
        tag: "chiayi_country",
        place: "嘉義縣",
        low: "暫無資料",
        high: "暫無資料",
        weather: "暫無資料",
        weatherIcon: 0,
        PoP: -1,
        AIQ: -1,
        Status: "暫無資料",
        PM25: -1
    },
    {
        tag: "pingtung_country",
        place: "屏東縣",
        low: "暫無資料",
        high: "暫無資料",
        weather: "暫無資料",
        weatherIcon: 0,
        PoP: -1,
        AIQ: -1,
        Status: "暫無資料",
        PM25: -1
    },
    {
        tag: "yilan_country",
        place: "宜蘭縣",
        low: "暫無資料",
        high: "暫無資料",
        weather: "暫無資料",
        weatherIcon: 0,
        PoP: -1,
        AIQ: -1,
        Status: "暫無資料",
        PM25: -1
    },
    {
        tag: "hualien_country",
        place: "花蓮縣",
        low: "暫無資料",
        high: "暫無資料",
        weather: "暫無資料",
        weatherIcon: 0,
        PoP: -1,
        AIQ: -1,
        Status: "暫無資料",
        PM25: -1
    },
    {
        tag: "taitung_country",
        place: "臺東縣",
        low: "暫無資料",
        high: "暫無資料",
        weather: "暫無資料",
        weatherIcon: 0,
        PoP: -1,
        AIQ: -1,
        Status: "暫無資料",
        PM25: -1
    },
    {
        tag: "penghu_country",
        place: "澎湖縣",
        low: "暫無資料",
        high: "暫無資料",
        weather: "暫無資料",
        weatherIcon: 0,
        PoP: -1,
        AIQ: -1,
        Status: "暫無資料",
        PM25: -1
    },
    {
        tag: "kinmen_country",
        place: "金門縣",
        low: "暫無資料",
        high: "暫無資料",
        weather: "暫無資料",
        weatherIcon: 0,
        PoP: -1,
        AIQ: -1,
        Status: "暫無資料",
        PM25: -1
    },
    {
        tag: "lienchiang_country",
        place: "連江縣",
        low: "暫無資料",
        high: "暫無資料",
        weather: "暫無資料",
        weatherIcon: 0,
        PoP: -1,
        AIQ: -1,
        Status: "暫無資料",
        PM25: -1
    }
];